### ISSUE TITLE
wat-go-sdk

### ISSUE THREAD

**Issue by HenryGeorgist** [USACE/wat-go-sdk#1]
# TODO

 1. Create __wat-go-sdk__ repository
 2. Add modules in the following order  
 - [x] plugin-manager
 - [x] job-manager
 - [x] #11
 - [x] #10

3. Once all modules are complete add contributing.

Branching strategy:
 - `feature/module-name` 
 - `bugfix/bug-name`

Development Tagging
- for feature adds bump minor version (e.g. v0.1.0)
- for module changes, updates, bugfixes, etc. bump patch (e.g. v0.1.1)

For initial development reviews required before merging into main.

Rules for testing: 
 - Mock test data always read from file. 

Development protocols:
 - use main.go function to interact with modules during development.
 - Then, write tests.

Documentation (readme etc) updated with each PR.

```Dockerfile
FROM golang:1.18.2-alpine3.15 AS dev

RUN apk add --update --no-cache

RUN go install github.com/githubnemo/CompileDaemon@v1.4.0

COPY ./ /app
WORKDIR /app

RUN go mod download
RUN go build main.go
```

```yaml
version: '3.8'

services:
  wat-go-sdk:
    container_name: wat-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    env_file:
      - ./.env
    entrypoint: |
      /go/bin/CompileDaemon --build="go build main.go" --command ./main
```
